/*
 * Airplane Hackathon API
 * Airplane Hackathon API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BoardScoreDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-09-28T10:57:44.889768+02:00[Europe/Warsaw]")
public class BoardScoreDTO {

  @SerializedName("name")
  private String name = null;
  
  @SerializedName("color")
  private String color = null;
  
  @SerializedName("score")
  private Long score = null;
  
  @SerializedName("percent")
  private Double percent = null;
  
  public BoardScoreDTO name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Get name
  * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public BoardScoreDTO color(String color) {
    this.color = color;
    return this;
  }

  
  /**
  * Get color
  * @return color
  **/
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }
  
  public BoardScoreDTO score(Long score) {
    this.score = score;
    return this;
  }

  
  /**
  * Get score
  * @return score
  **/
  @ApiModelProperty(value = "")
  public Long getScore() {
    return score;
  }
  public void setScore(Long score) {
    this.score = score;
  }
  
  public BoardScoreDTO percent(Double percent) {
    this.percent = percent;
    return this;
  }

  
  /**
  * Get percent
  * @return percent
  **/
  @ApiModelProperty(value = "")
  public Double getPercent() {
    return percent;
  }
  public void setPercent(Double percent) {
    this.percent = percent;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardScoreDTO boardScoreDTO = (BoardScoreDTO) o;
    return Objects.equals(this.name, boardScoreDTO.name) &&
        Objects.equals(this.color, boardScoreDTO.color) &&
        Objects.equals(this.score, boardScoreDTO.score) &&
        Objects.equals(this.percent, boardScoreDTO.percent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, color, score, percent);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardScoreDTO {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



