/*
 * Airplane Hackathon API
 * Airplane Hackathon API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BoardScoreDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BoardScoresDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-09-28T10:57:44.889768+02:00[Europe/Warsaw]")
public class BoardScoresDTO {

  @SerializedName("scores")
  private List<BoardScoreDTO> scores = null;
  
  @SerializedName("maxScore")
  private Integer maxScore = null;
  
  public BoardScoresDTO scores(List<BoardScoreDTO> scores) {
    this.scores = scores;
    return this;
  }

  public BoardScoresDTO addScoresItem(BoardScoreDTO scoresItem) {
    
    if (this.scores == null) {
      this.scores = new ArrayList<BoardScoreDTO>();
    }
    
    this.scores.add(scoresItem);
    return this;
  }
  
  /**
  * Get scores
  * @return scores
  **/
  @ApiModelProperty(value = "")
  public List<BoardScoreDTO> getScores() {
    return scores;
  }
  public void setScores(List<BoardScoreDTO> scores) {
    this.scores = scores;
  }
  
  public BoardScoresDTO maxScore(Integer maxScore) {
    this.maxScore = maxScore;
    return this;
  }

  
  /**
  * Get maxScore
  * @return maxScore
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxScore() {
    return maxScore;
  }
  public void setMaxScore(Integer maxScore) {
    this.maxScore = maxScore;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardScoresDTO boardScoresDTO = (BoardScoresDTO) o;
    return Objects.equals(this.scores, boardScoresDTO.scores) &&
        Objects.equals(this.maxScore, boardScoresDTO.maxScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scores, maxScore);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardScoresDTO {\n");
    
    sb.append("    scores: ").append(toIndentedString(scores)).append("\n");
    sb.append("    maxScore: ").append(toIndentedString(maxScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



