/*
 * Airplane Hackathon API
 * Airplane Hackathon API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BoardGeneralDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BoardAllGeneralDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-09-28T10:57:44.889768+02:00[Europe/Warsaw]")
public class BoardAllGeneralDTO {

  @SerializedName("boards")
  private List<BoardGeneralDTO> boards = null;
  
  public BoardAllGeneralDTO boards(List<BoardGeneralDTO> boards) {
    this.boards = boards;
    return this;
  }

  public BoardAllGeneralDTO addBoardsItem(BoardGeneralDTO boardsItem) {
    
    if (this.boards == null) {
      this.boards = new ArrayList<BoardGeneralDTO>();
    }
    
    this.boards.add(boardsItem);
    return this;
  }
  
  /**
  * Get boards
  * @return boards
  **/
  @ApiModelProperty(value = "")
  public List<BoardGeneralDTO> getBoards() {
    return boards;
  }
  public void setBoards(List<BoardGeneralDTO> boards) {
    this.boards = boards;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardAllGeneralDTO boardAllGeneralDTO = (BoardAllGeneralDTO) o;
    return Objects.equals(this.boards, boardAllGeneralDTO.boards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boards);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardAllGeneralDTO {\n");
    
    sb.append("    boards: ").append(toIndentedString(boards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



