/*
 * Airplane Hackathon API
 * Airplane Hackathon API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * PassengerDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-09-28T10:57:44.889768+02:00[Europe/Warsaw]")
public class PassengerDTO {

  @SerializedName("id")
  private UUID id = null;
  
  @SerializedName("x")
  private Integer x = null;
  
  @SerializedName("y")
  private Integer y = null;
  
  @SerializedName("takenBy")
  private String takenBy = null;
  
  @SerializedName("takenByColor")
  private String takenByColor = null;
  
  public PassengerDTO id(UUID id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }
  
  public PassengerDTO x(Integer x) {
    this.x = x;
    return this;
  }

  
  /**
  * Get x
  * @return x
  **/
  @ApiModelProperty(value = "")
  public Integer getX() {
    return x;
  }
  public void setX(Integer x) {
    this.x = x;
  }
  
  public PassengerDTO y(Integer y) {
    this.y = y;
    return this;
  }

  
  /**
  * Get y
  * @return y
  **/
  @ApiModelProperty(value = "")
  public Integer getY() {
    return y;
  }
  public void setY(Integer y) {
    this.y = y;
  }
  
  public PassengerDTO takenBy(String takenBy) {
    this.takenBy = takenBy;
    return this;
  }

  
  /**
  * Get takenBy
  * @return takenBy
  **/
  @ApiModelProperty(value = "")
  public String getTakenBy() {
    return takenBy;
  }
  public void setTakenBy(String takenBy) {
    this.takenBy = takenBy;
  }
  
  public PassengerDTO takenByColor(String takenByColor) {
    this.takenByColor = takenByColor;
    return this;
  }

  
  /**
  * Get takenByColor
  * @return takenByColor
  **/
  @ApiModelProperty(value = "")
  public String getTakenByColor() {
    return takenByColor;
  }
  public void setTakenByColor(String takenByColor) {
    this.takenByColor = takenByColor;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassengerDTO passengerDTO = (PassengerDTO) o;
    return Objects.equals(this.id, passengerDTO.id) &&
        Objects.equals(this.x, passengerDTO.x) &&
        Objects.equals(this.y, passengerDTO.y) &&
        Objects.equals(this.takenBy, passengerDTO.takenBy) &&
        Objects.equals(this.takenByColor, passengerDTO.takenByColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, x, y, takenBy, takenByColor);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassengerDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    takenBy: ").append(toIndentedString(takenBy)).append("\n");
    sb.append("    takenByColor: ").append(toIndentedString(takenByColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



