/*
 * Airplane Hackathon API
 * Airplane Hackathon API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AirplaneRegisterRequestDTO;
import io.swagger.client.model.AirplaneRegisterResponseDTO;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AirplaneControllerApi
 */
@Ignore
public class AirplaneControllerApiTest {

    private final AirplaneControllerApi api = new AirplaneControllerApi();

    
    /**
     * At first, please register yor Airplane. Name and color are unique. Color means HTML color e.g. #CCC, #ABABAB etc.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void register1Test() throws ApiException {
        
        AirplaneRegisterRequestDTO body = null;
        
        AirplaneRegisterResponseDTO response = api.register1(body);

        // TODO: test validations
    }
    
}
